version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    # command: bash -c "cd /src/rest && python manage.py makemigrations && python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      # - ${ADBREW_CODEBASE_PATH}:/src
      - /home/sarthak/Documents/Documents/Web Development/Adbrew Test/adb_test/src:/src
    # - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - /home/sarthak/Documents/Documents/Web Development/Adbrew Test/adb_test/src/tmp:/tmp

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - /home/sarthak/Documents/Documents/Web Development/Adbrew Test/adb_test/src:/src

  mongo:
    build: .
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

  